title: AWS AppSync SDK for iOS
description: The AWS AppSync SDK for iOS enables you to access your AWS AppSync backend and perform operations like Queries, Mutations, and Subscriptions. The SDK also includes support for offline operations.
url: "https://awslabs.github.io/aws-mobile-appsync-sdk-ios/"

github:
  repository_url: "https://github.com/awslabs/aws-mobile-appsync-sdk-ios/tree/master/docs"

plugins:
  - jekyll-redirect-from

markdown: kramdown
kramdown:
  parse_block_html: true

exclude:
  - Gemfile
  - Gemfile.lock
